name: PHP

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Composer dependencies
        run: composer update

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install dependencies
        working-directory: ./src
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run unit tests
        run: php vendor/bin/codecept run unit
